#!/bin/sh

# chkconfig: 345 10 90
# description: tomcat6 service

#exec /srv/apache-tomcat-6.0.48/bin/catalina.sh start

case $1 in
	start)
		if [[ $(ps aux|grep "apache-tomcat-6.0.48"|grep -v "grep") != "" ]];then
                        echo -e "\033[32mTomcat6\033[0m has been running..."
                else
			/srv/apache-tomcat-6.0.48/bin/catalina.sh start
		fi
		;;
	stop)
		/srv/apache-tomcat-6.0.48/bin/catalina.sh stop
		;;
	restart)
		/srv/apache-tomcat-6.0.48/bin/catalina.sh stop && /srv/apache-tomcat-6.0.48/bin/catalina.sh start
		;;
	status)
		if [[ $(ps aux|grep "apache-tomcat-6.0.48"|grep -v "grep") != "" ]];then
			echo -e "\033[32mTomcat6\033[0m (pid $(ps aux|grep "apache-tomcat"|grep -v "grep"|awk '{print $2}')) is running..."
		else
			echo -e "\033[32mTomcat6\033[0m is stop"
		fi
		;;
	*)
		echo -e $"Useage: $0 {\033[32mstart\033[0m|\033[32mstop\033[0m|\033[32mrestart\033[0m}"
		exit 2
		;;
esac
